server {
    listen 80;
    listen 443 ssl;
    server_name *.nuvads.test *.nuvads.ai;
    root /var/www/html/public;
    index index.php index.html;

    ssl_certificate /etc/nginx/certs/nuvads-local.pem;
    ssl_certificate_key /etc/nginx/certs/nuvads-local-key.pem;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /index.php {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS $https if_not_empty;
        fastcgi_hide_header X-Powered-By;
    }

    location ~ \.php(?:/|$) {
        return 404;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
